version: '3.9'

services:
  nginx:
    image: nginx:alpine
    container_name: reverse_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - backend
    networks:
      - secure_network

  backend:
    build: ./backend
    image: securenotes_backend:latest
    container_name: secure_backend
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./backend:/app
    expose:
      - "8000"
    networks:
      - secure_network

  db:
    image: postgres:alpine
    container_name: secure_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - secure_network

networks:
  secure_network:
    driver: bridge

volumes:
  db_data:
