name: SecureNotes CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-and-analyze:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_DB: securenotes
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Lint with flake8
      run: |
        source venv/bin/activate
        flake8 backend/

    - name: Run Bandit security scan
      run: |
        source venv/bin/activate
        bandit -r backend/

    - name: Run pytest
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/securenotes
        SECRET_KEY: CiberSeg
      run: |
        source venv/bin/activate
        pytest backend/test_app.py

    - name: Install Trivy
      run: |
        sudo apt-get update && sudo apt-get install -y wget
        wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.49.1_Linux-64bit.deb
        sudo dpkg -i trivy_0.49.1_Linux-64bit.deb

    - name: Scan backend Docker image with Trivy
      run: |
        docker build -t securenotes_backend backend/
        trivy image --severity HIGH,CRITICAL securenotes_backend || true
